// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZBE6o_7wz_XXV224_TbW-R4LWv5d2oE',
    appId: '1:236143786082:web:031a5d3e3c6875dfd5393b',
    messagingSenderId: '236143786082',
    projectId: 'grownidhi-app',
    authDomain: 'grownidhi-app.firebaseapp.com',
    storageBucket: 'grownidhi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBcbrj9raee-9fPUdHP4lmTlDftNEU5E',
    appId: '1:236143786082:android:c8575ce849e18f0ed5393b',
    messagingSenderId: '236143786082',
    projectId: 'grownidhi-app',
    storageBucket: 'grownidhi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5CuE7b8z4Sj84IYtvNcqmv3VE7mdYSjg',
    appId: '1:236143786082:ios:62a56fe2f3ac2148d5393b',
    messagingSenderId: '236143786082',
    projectId: 'grownidhi-app',
    storageBucket: 'grownidhi-app.firebasestorage.app',
    iosBundleId: 'com.technowxa.appGrownidhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5CuE7b8z4Sj84IYtvNcqmv3VE7mdYSjg',
    appId: '1:236143786082:ios:62a56fe2f3ac2148d5393b',
    messagingSenderId: '236143786082',
    projectId: 'grownidhi-app',
    storageBucket: 'grownidhi-app.firebasestorage.app',
    iosBundleId: 'com.technowxa.appGrownidhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ZBE6o_7wz_XXV224_TbW-R4LWv5d2oE',
    appId: '1:236143786082:web:f1a590ddafc32efbd5393b',
    messagingSenderId: '236143786082',
    projectId: 'grownidhi-app',
    authDomain: 'grownidhi-app.firebaseapp.com',
    storageBucket: 'grownidhi-app.firebasestorage.app',
  );
}
